# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sophie Clayton
tagline:          Bio-Physical Interactions in the Ocean
description:      "Researching bio-physical interactions in the oceans, playing with code and seawater"
url:              http:sophieclayton.github.io
paginate:         3
baseurl:          /
author:
  name:           Sophie Clayton
  url:            http://sophieclayton.github.io
  email:          sclayton@uw.edu

