# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sophie Clayton
tagline:          Researching bio-physical interactions in the oceans
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Sophie Clayton
  url:            http://sophieclayton.github.io
  email:          sclayton@uw.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
