# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Sophie Clayton"
tagline:          "Bio-Physical Interactions in the Oceans"
description:      "Researching bio-physical interactions in the oceans, playing with code and seawater"
url:              http://sophieclayton.github.io/
baseurl:          
paginate:         3
avatar_url:       https://raw.githubusercontent.com/sophieclayton/sophieclayton.github.io/master/images/avatar.jpg

author:
  name:           Sophie Clayton
  url:            http://sophieclayton.github.io
  email:          sclayton@uw.edu

